# Generated by Django 5.2.1 on 2025-05-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('checkmark', models.CharField(max_length=100)),
            ],
        ),
    ]
